SET(PHYSFS_BUILD_STATIC ON CACHE BOOL "" FORCE)
SET(PHYSFS_BUILD_SHARED OFF CACHE BOOL "" FORCE)
SET(PHYSFS_BUILD_TEST OFF CACHE BOOL "" FORCE)
SET(PHYSFS_BUILD_DOCS OFF CACHE BOOL "" FORCE)
SET(PHYSFS_DISABLE_INSTALL ON CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_7Z OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_GRP OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_HOG OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_ISO9660 OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_MVL OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_QPAK OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_SLB OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_VDF OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_CSM OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_WAD OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_POD OFF CACHE BOOL "" FORCE)
SET(PHYSFS_ARCHIVE_LECARCHIVES OFF CACHE BOOL "" FORCE)

# Fetch PhysicsFS
FETCHCONTENT_DECLARE(
  physfs
  URL https://github.com/icculus/physfs/archive/refs/heads/master.zip
)
FETCHCONTENT_MAKEAVAILABLE(physfs)

# Fetch raylib
FETCHCONTENT_DECLARE(
    raylib
    URL https://github.com/raysan5/raylib/archive/refs/tags/5.5.zip
)
FETCHCONTENT_MAKEAVAILABLE(raylib)

# Fetch raylib-physfs
FETCHCONTENT_DECLARE(
    raylib_physfs
    URL https://github.com/RobLoach/raylib-physfs/archive/refs/heads/master.zip
)
FETCHCONTENT_MAKEAVAILABLE(raylib_physfs)


# Main executable
FILE(GLOB SRC_FILES *.c)
ADD_EXECUTABLE(host ${SRC_FILES})
SET_TARGET_PROPERTIES(host PROPERTIES OUTPUT_NAME ${PROJECT_NAME})

# Link PhysicsFS static library & raylib
TARGET_LINK_LIBRARIES(host PRIVATE physfs-static raylib raylib_physfs)

# Emscripten-specific settings
IF(EMSCRIPTEN)
  TARGET_LINK_OPTIONS(host PRIVATE 
    -sALLOW_MEMORY_GROWTH=1
    -sEXPORTED_RUNTIME_METHODS=FS,HEAPU8
    -sSINGLE_FILE=1
    -sASYNCIFY
    -sASSERTIONS=1
    -sEXPORTED_FUNCTIONS=@${CMAKE_SOURCE_DIR}/host/web_exports.txt
  )

  SET(CMAKE_EXECUTABLE_SUFFIX ".mjs")

  ADD_CUSTOM_COMMAND(TARGET host POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:host> ${CMAKE_SOURCE_DIR}/demo/
    COMMENT "Copying host files to docs webroot"
  )
ELSE()
  # Fetch wamr for native wasm-host
  STRING(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} WAMR_BUILD_PLATFORM)
  SET (WAMR_BUILD_INTERP 1)
  SET (WAMR_BUILD_DEBUG_INTERP 0)
  SET (WAMR_BUILD_FAST_INTERP 1)
  SET (WAMR_BUILD_AOT 0)
  SET (WAMR_BUILD_LIBC_BUILTIN 0)
  SET (WAMR_BUILD_LIBC_WASI 0)
  IF(NOT DEFINED WAMR_BUILD_SIMD)
    SET (WAMR_BUILD_SIMD 1)
  ENDIF()
  SET (WAMR_BUILD_REF_TYPES 1)

  FETCHCONTENT_DECLARE(wamr
    URL https://github.com/bytecodealliance/wasm-micro-runtime/archive/refs/heads/master.zip
  )
  FETCHCONTENT_MAKEAVAILABLE(wamr)
  INCLUDE (${wamr_SOURCE_DIR}/build-scripts/runtime_lib.cmake)

  # Link to wamr on native
  TARGET_LINK_LIBRARIES(host PRIVATE vmlib)
ENDIF()