FIND_PACKAGE(physfs REQUIRED)
FIND_PACKAGE(raylib REQUIRED)

FILE(GLOB SRC_FILES *.c)
add_executable(host ${SRC_FILES})
set_target_properties(host PROPERTIES OUTPUT_NAME ${PROJECT_NAME})
TARGET_LINK_LIBRARIES(host physfs-static raylib)

IF (EMSCRIPTEN)
  SET(CMAKE_EXECUTABLE_SUFFIX ".mjs")
  TARGET_LINK_OPTIONS(host PRIVATE -sEXPORTED_FUNCTIONS=@${CMAKE_SOURCE_DIR}/host/web_exports.txt -sFORCE_FILESYSTEM -sEXPORTED_RUNTIME_METHODS=FS,HEAPU8,HEAPU32,stringToNewUTF8 -sSINGLE_FILE=1 -sASSERTIONS=1 -sASYNCIFY -sALLOW_MEMORY_GROWTH=1)
  ADD_CUSTOM_COMMAND(
    TARGET host
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
            $<TARGET_FILE:host>
            ${CMAKE_SOURCE_DIR}/demo/
    COMMENT "Copying host files to demo webroot"
  )
ELSE()
  FIND_PACKAGE(wamr REQUIRED)
  TARGET_LINK_LIBRARIES(host vmlib)
ENDIF()